# # This workflow will build a Swift project
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# name: Build Test

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v

name: Build-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          xcodebuild clean build -project WorkflowTest.xcodeproj -scheme WorkflowTest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      # - name: Test
      #   run: |
      #     xcodebuild clean test -project "Workflow Test".xcodeproj -scheme GHFollowersTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      #   env: 
      #    destination: ${{ matrix.destination }}